script: ./build.sh
cache: apt
dist: trusty
before_script:
  - curl https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2 | tar -C /home/travis -x -j
  - export PATH=$PATH:/home/travis/gcc-arm-none-eabi-6-2017-q2-update/bin
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - source /home/travis/.cargo/env
  - pushd /
  - rustup component add rust-src
  - cargo install xargo
  - popd
