[package]
name = "bare-metal-arm-rust"
version = "0.2.2"
authors = [
	"Michael Daffin <michael@daffin.io>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"
]
build = "build.rs"
keywords = ["arm", "bare-metal", "blink"]
license = "MIT"
readme = "README.md"

[dependencies]
primer = { path = "primer" }
rust-libcore = { git = "https://github.com/hackndev/rust-libcore" }
