[package]
authors = [
	"Michael Daffin <michael@daffin.io>",
	"Philipp Oppermann <dev@phil-opp.com>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>",
	"Marc Brinkmann"
]
keywords = ["arm", "bare-metal", "blink", "lm4f120"]
license = "MIT"
name = "launchpad"
readme = "README.md"
version = "0.5.0"

# The development profile, used for `cargo build`.
[profile.dev]
panic = "abort"

# The release profile, used for `cargo build --release`.
[profile.release]
panic = "abort"
debug = true
lto = true

[dependencies]
linked_list_allocator = "^0.2"
spin = "^0.4"
r0 = "^0.1.0"
cortex-m = { git = "https://github.com/thejpster/cortex-m.git" }
volatile-register = "^0.1.2"

[dependencies.compiler_builtins]
git = "https://github.com/rust-lang-nursery/compiler-builtins.git"
features = [ "weak" ]

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "^0.2"

[dependencies.rlibc]
version = "^1.0"
