[package]
authors = [
	"Michael Daffin <michael@daffin.io>",
	"Philipp Oppermann <dev@phil-opp.com>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>",
	"Marc Brinkmann"
]
keywords = ["arm", "bare-metal", "blink"]
license = "MIT"
name = "primer"
readme = "README.md"
version = "0.4.0"

[features]
# Support the LM4F120 Stellaris/Tiva-C Launchpad
# Use the lm4f120 target
launchpad = []
# Support the Maple Labs Leaf Mini
# Use the stm32f103 target
leaf_mini = []
default = ["launchpad"]

# The development profile, used for `cargo build`.
[profile.dev]
panic = "abort"

# The release profile, used for `cargo build --release`.
[profile.release]
panic = "abort"
debug = true

[dependencies]
linked_list_allocator = "^0.2"
spin = "^0.4"

[dependencies.rustc_builtins]
git = "https://github.com/japaric/rustc-builtins.git"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "^0.2"

[dependencies.rlibc]
version = "^1.0"
