[package]
name = "bare-metal-arm-rust"
version = "0.2.2"
authors = [
	"Michael Daffin <michael@daffin.io>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"
]
build = "build.rs"
keywords = ["arm", "bare-metal", "blink"]
license = "MIT"
readme = "README.md"

[dependencies]
primer = { path = "primer" }

# The development profile, used for `cargo build`.
[profile.dev]
panic = "abort"

# The release profile, used for `cargo build --release`.
[profile.release]
panic = "abort"
