[package]
authors = [
	"Michael Daffin <michael@daffin.io>",
	"Philipp Oppermann <dev@phil-opp.com>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>",
	"Marc Brinkmann"
]
keywords = ["arm", "bare-metal", "bootloader", "lm4f120", "launchpad"]
license = "MIT"
name = "stellaris-launchpad-bootloader"
readme = "README.md"
version = "0.1.0"
description = "A Tockloader compatible bootloader for the Texas Instruments Stellaris LM4F120 Launchpad (and most likely the Tiva-C TM4C120 Launchpad too)"
repository = "https://github.com/thejpster/stellaris-launchpad-bootloader"
categories = ["hardware-support"]
homepage = "https://www.thejpster.org.uk"

# The development profile, used for `cargo build`.
[profile.dev]
panic = "abort"
debug = true
lto = true

# The release profile, used for `cargo build --release`.
[profile.release]
panic = "abort"
debug = true
lto = true

[dependencies]
r0 = "0.2.2"
alloc-cortex-m = "0.3.0"
cortex-m = "0.3.1"
lm4f120 = "0.5.1"
embedded-serial = "0.5.0"
# tockloader-proto = { path = "../tockloader-proto" }
tockloader-proto = "0.1"

[badges]
travis-ci = { repository = "thejpster/stellaris-launchpad-bootloader", branch = "master" }

[[bin]]
name = "bootloader"
path = "./src/main.rs"
crate-type = ["staticlib"]
