[package]
name = "bare-metal-arm-rust"
version = "0.2.0"
authors = [
	"Michael Daffin <michael@daffin.io>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"
]
build = "build.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 2
debug = false

[target.thumbv7em-none-eabi.dependencies.rust-libcore]
git = "https://github.com/hackndev/rust-libcore"

[dependencies]
primer = { path = "primer" }
