[package]
name = "bare-metal-arm-rust"
version = "0.2.1"
authors = [
	"Michael Daffin <michael@daffin.io>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"
]
build = "build.rs"
keywords = ["arm", "bare-metal", "blink"]
license = "MIT"
readme = "README.md"

[target.thumbv7em-none-eabi.dependencies.rust-libcore]
git = "https://github.com/hackndev/rust-libcore"

[dependencies]
primer = { path = "primer" }
