[package]
authors = [
	"Michael Daffin <michael@daffin.io>",
	"Philipp Oppermann <dev@phil-opp.com>",
	"Jonathan 'theJPster' Pallant <github@thejpster.org.uk>",
	"Marc Brinkmann"
]
keywords = ["arm", "bare-metal", "blink", "lm4f120"]
license = "MIT"
name = "stellaris-launchpad"
readme = "README.md"
version = "0.5.6"
description = "A bare-metal crate supporting the Texas Instruments Stellaris LM4F120 Launchpad (and most likely the Tiva-C TM4C120 Launchpad too)"

# The development profile, used for `cargo build`.
[profile.dev]
panic = "abort"

# The release profile, used for `cargo build --release`.
[profile.release]
panic = "abort"
debug = true
lto = true

[dependencies]
r0 = "0.1.0"
cortex-m = "0.1.5"
volatile-register = "0.1.2"
lm4f120 = "0.2.0"
embedded-serial = "0.3.0"
alloc-cortex-m = "0.2.0"
rlibc = "1.0"

[dependencies.compiler-builtins-snapshot]
version = "0.1"
features = [ "mem" ]

[badges]
travis-ci = { repository = "thejpster/launchpad-rs", branch = "master" }
